/*
印尼个省市地名，用于级联选择地区
 */

 const Address=[
    {Province:"Aceh",City:"Aceh Barat"},
    {Province:"Aceh",City:"Aceh Barat Daya"},
    {Province:"Aceh",City:"Aceh Besar"},
    {Province:"Aceh",City:"Aceh Jaya"},
    {Province:"Aceh",City:"Aceh Selatan"},
    {Province:"Aceh",City:"Aceh Singkil"},
    {Province:"Aceh",City:"Aceh Tamiang"},
    {Province:"Aceh",City:"Aceh Tengah"},
    {Province:"Aceh",City:"Aceh Tenggara"},
    {Province:"Aceh",City:"Aceh Timur"},
    {Province:"Aceh",City:"Aceh Utara"},
    {Province:"Aceh",City:"Banda Aceh"},
    {Province:"Aceh",City:"Bener Meriah"},
    {Province:"Aceh",City:"Bireuen"},
    {Province:"Aceh",City:"Gayo Lues"},
    {Province:"Aceh",City:"Lhokseumawe"},
    {Province:"Aceh",City:"Nagan Raya"},
    {Province:"Aceh",City:"Pidie"},
    {Province:"Aceh",City:"Pidie Jaya"},
    {Province:"Aceh",City:"Sabang"},
    {Province:"Aceh",City:"Simeulue"},
    {Province:"Aceh",City:"Subulussalam"},
    {Province:"Bali",City:"Badung"},
    {Province:"Bali",City:"Bangli"},
    {Province:"Bali",City:"Buleleng"},
    {Province:"Bali",City:"Denpasar"},
    {Province:"Bali",City:"Gianyar"},
    {Province:"Bali",City:"Jembrana"},
    {Province:"Bali",City:"Karangasem"},
    {Province:"Bali",City:"Klungkung"},
    {Province:"Bali",City:"Tabanan"},
    {Province:"Bangka Belitung",City:"Bangka"},
    {Province:"Bangka Belitung",City:"Bangka Barat"},
    {Province:"Bangka Belitung",City:"Bangka Selatan"},
    {Province:"Bangka Belitung",City:"Bangka Tengah"},
    {Province:"Bangka Belitung",City:"Belitung"},
    {Province:"Bangka Belitung",City:"Belitung Timur"},
    {Province:"Bangka Belitung",City:"Pangkal Pinang"},
    {Province:"Banten",City:"Cilegon"},
    {Province:"Banten",City:"Lebak"},
    {Province:"Banten",City:"Pandeglang"},
    {Province:"Banten",City:"Serang"},
    {Province:"Banten",City:"Tangerang"},
    {Province:"Banten",City:"Tangerang Selatan"},
    {Province:"Bengkulu",City:"Bengkulu"},
    {Province:"Bengkulu",City:"Bengkulu Selatan"},
    {Province:"Bengkulu",City:"Bengkulu Tengah"},
    {Province:"Bengkulu",City:"Bengkulu Utara"},
    {Province:"Bengkulu",City:"Kaur"},
    {Province:"Bengkulu",City:"Kepahiang"},
    {Province:"Bengkulu",City:"Lebong"},
    {Province:"Bengkulu",City:"Muko Muko"},
    {Province:"Bengkulu",City:"Rejang Lebong"},
    {Province:"Bengkulu",City:"Seluma"},
    {Province:"DI Yogyakarta",City:"Bantul"},
    {Province:"DI Yogyakarta",City:"Gunung Kidul"},
    {Province:"DI Yogyakarta",City:"Kulon Progo"},
    {Province:"DI Yogyakarta",City:"Sleman"},
    {Province:"DI Yogyakarta",City:"Yogyakarta"},
    {Province:"DKI Jakarta",City:"Jakarta Barat"},
    {Province:"DKI Jakarta",City:"Jakarta Pusat"},
    {Province:"DKI Jakarta",City:"Jakarta Selatan"},
    {Province:"DKI Jakarta",City:"Jakarta Timur"},
    {Province:"DKI Jakarta",City:"Jakarta Utara"},
    {Province:"DKI Jakarta",City:"Kepulauan Seribu"},
    {Province:"Gorontalo",City:"Boalemo"},
    {Province:"Gorontalo",City:"Bone Bolango"},
    {Province:"Gorontalo",City:"Gorontalo"},
    {Province:"Gorontalo",City:"Gorontalo Utara"},
    {Province:"Gorontalo",City:"Pohuwato"},
    {Province:"Jambi",City:"Batang Hari"},
    {Province:"Jambi",City:"Bungo"},
    {Province:"Jambi",City:"Jambi"},
    {Province:"Jambi",City:"Kerinci"},
    {Province:"Jambi",City:"Merangin"},
    {Province:"Jambi",City:"Muaro Jambi"},
    {Province:"Jambi",City:"Sarolangun"},
    {Province:"Jambi",City:"Sungaipenuh"},
    {Province:"Jambi",City:"Tanjung Jabung Barat"},
    {Province:"Jambi",City:"Tanjung Jabung Timur"},
    {Province:"Jambi",City:"Tebo"},
    {Province:"Jawa Barat",City:"Bandung"},
    {Province:"Jawa Barat",City:"Bandung Barat"},
    {Province:"Jawa Barat",City:"Banjar"},
    {Province:"Jawa Barat",City:"Bekasi"},
    {Province:"Jawa Barat",City:"Bogor"},
    {Province:"Jawa Barat",City:"Ciamis"},
    {Province:"Jawa Barat",City:"Cianjur"},
    {Province:"Jawa Barat",City:"Cimahi"},
    {Province:"Jawa Barat",City:"Cirebon"},
    {Province:"Jawa Barat",City:"Depok"},
    {Province:"Jawa Barat",City:"Garut"},
    {Province:"Jawa Barat",City:"Indramayu"},
    {Province:"Jawa Barat",City:"Karawang"},
    {Province:"Jawa Barat",City:"Kuningan"},
    {Province:"Jawa Barat",City:"Majalengka"},
    {Province:"Jawa Barat",City:"Pangandaran"},
    {Province:"Jawa Barat",City:"Purwakarta"},
    {Province:"Jawa Barat",City:"Subang"},
    {Province:"Jawa Barat",City:"Sukabumi"},
    {Province:"Jawa Barat",City:"Sumedang"},
    {Province:"Jawa Barat",City:"Tasikmalaya"},
    {Province:"Jawa Tengah",City:"Banjarnegara"},
    {Province:"Jawa Tengah",City:"Banyumas"},
    {Province:"Jawa Tengah",City:"Batang"},
    {Province:"Jawa Tengah",City:"Blora"},
    {Province:"Jawa Tengah",City:"Boyolali"},
    {Province:"Jawa Tengah",City:"Brebes"},
    {Province:"Jawa Tengah",City:"Cilacap"},
    {Province:"Jawa Tengah",City:"Demak"},
    {Province:"Jawa Tengah",City:"Grobogan"},
    {Province:"Jawa Tengah",City:"Jepara"},
    {Province:"Jawa Tengah",City:"Karanganyar"},
    {Province:"Jawa Tengah",City:"Kebumen"},
    {Province:"Jawa Tengah",City:"Kendal"},
    {Province:"Jawa Tengah",City:"Klaten"},
    {Province:"Jawa Tengah",City:"Kudus"},
    {Province:"Jawa Tengah",City:"Magelang"},
    {Province:"Jawa Tengah",City:"Pati"},
    {Province:"Jawa Tengah",City:"Pekalongan"},
    {Province:"Jawa Tengah",City:"Pemalang"},
    {Province:"Jawa Tengah",City:"Purbalingga"},
    {Province:"Jawa Tengah",City:"Purworejo"},
    {Province:"Jawa Tengah",City:"Rembang"},
    {Province:"Jawa Tengah",City:"Salatiga"},
    {Province:"Jawa Tengah",City:"Semarang"},
    {Province:"Jawa Tengah",City:"Sragen"},
    {Province:"Jawa Tengah",City:"Sukoharjo"},
    {Province:"Jawa Tengah",City:"Surakarta"},
    {Province:"Jawa Tengah",City:"Tegal"},
    {Province:"Jawa Tengah",City:"Temanggung"},
    {Province:"Jawa Tengah",City:"Wonogiri"},
    {Province:"Jawa Tengah",City:"Wonosobo"},
    {Province:"Jawa Timur",City:"Bangkalan"},
    {Province:"Jawa Timur",City:"Banyuwangi"},
    {Province:"Jawa Timur",City:"Batu"},
    {Province:"Jawa Timur",City:"Blitar"},
    {Province:"Jawa Timur",City:"Bojonegoro"},
    {Province:"Jawa Timur",City:"Bondowoso"},
    {Province:"Jawa Timur",City:"Gresik"},
    {Province:"Jawa Timur",City:"Jember"},
    {Province:"Jawa Timur",City:"Jombang"},
    {Province:"Jawa Timur",City:"Kediri"},
    {Province:"Jawa Timur",City:"Lamongan"},
    {Province:"Jawa Timur",City:"Lumajang"},
    {Province:"Jawa Timur",City:"Madiun"},
    {Province:"Jawa Timur",City:"Magetan"},
    {Province:"Jawa Timur",City:"Malang"},
    {Province:"Jawa Timur",City:"Mojokerto"},
    {Province:"Jawa Timur",City:"Nganjuk"},
    {Province:"Jawa Timur",City:"Ngawi"},
    {Province:"Jawa Timur",City:"Pacitan"},
    {Province:"Jawa Timur",City:"Pamekasan"},
    {Province:"Jawa Timur",City:"Pasuruan"},
    {Province:"Jawa Timur",City:"Ponorogo"},
    {Province:"Jawa Timur",City:"Probolinggo"},
    {Province:"Jawa Timur",City:"Sampang"},
    {Province:"Jawa Timur",City:"Sidoarjo"},
    {Province:"Jawa Timur",City:"Situbondo"},
    {Province:"Jawa Timur",City:"Sumenep"},
    {Province:"Jawa Timur",City:"Surabaya"},
    {Province:"Jawa Timur",City:"Trenggalek"},
    {Province:"Jawa Timur",City:"Tuban"},
    {Province:"Jawa Timur",City:"Tulungagung"},
    {Province:"Kalimantan Barat",City:"Bengkayang"},
    {Province:"Kalimantan Barat",City:"Kapuas Hulu"},
    {Province:"Kalimantan Barat",City:"Kayong Utara"},
    {Province:"Kalimantan Barat",City:"Ketapang"},
    {Province:"Kalimantan Barat",City:"Kubu Raya"},
    {Province:"Kalimantan Barat",City:"Landak"},
    {Province:"Kalimantan Barat",City:"Melawi"},
    {Province:"Kalimantan Barat",City:"Mempawah"},
    {Province:"Kalimantan Barat",City:"Pontianak"},
    {Province:"Kalimantan Barat",City:"Sambas"},
    {Province:"Kalimantan Barat",City:"Sanggau"},
    {Province:"Kalimantan Barat",City:"Sekadau"},
    {Province:"Kalimantan Barat",City:"Singkawang"},
    {Province:"Kalimantan Barat",City:"Sintang"},
    {Province:"Kalimantan Selatan",City:"Balangan"},
    {Province:"Kalimantan Selatan",City:"Banjar"},
    {Province:"Kalimantan Selatan",City:"Banjarbaru"},
    {Province:"Kalimantan Selatan",City:"Banjarmasin"},
    {Province:"Kalimantan Selatan",City:"Barito Kuala"},
    {Province:"Kalimantan Selatan",City:"Hulu Sungai Selatan"},
    {Province:"Kalimantan Selatan",City:"Hulu Sungai Tengah"},
    {Province:"Kalimantan Selatan",City:"Hulu Sungai Utara"},
    {Province:"Kalimantan Selatan",City:"Kotabaru"},
    {Province:"Kalimantan Selatan",City:"Tabalong"},
    {Province:"Kalimantan Selatan",City:"Tanah Bumbu"},
    {Province:"Kalimantan Selatan",City:"Tanah Laut"},
    {Province:"Kalimantan Selatan",City:"Tapin"},
    {Province:"Kalimantan Tengah",City:"Barito Selatan"},
    {Province:"Kalimantan Tengah",City:"Barito Timur"},
    {Province:"Kalimantan Tengah",City:"Barito Utara"},
    {Province:"Kalimantan Tengah",City:"Gunung Mas"},
    {Province:"Kalimantan Tengah",City:"Kapuas"},
    {Province:"Kalimantan Tengah",City:"Katingan"},
    {Province:"Kalimantan Tengah",City:"Kotawaringin Barat"},
    {Province:"Kalimantan Tengah",City:"Kotawaringin Timur"},
    {Province:"Kalimantan Tengah",City:"Lamandau"},
    {Province:"Kalimantan Tengah",City:"Murung Raya"},
    {Province:"Kalimantan Tengah",City:"Palangka Raya"},
    {Province:"Kalimantan Tengah",City:"Pulang Pisau"},
    {Province:"Kalimantan Tengah",City:"Seruyan"},
    {Province:"Kalimantan Tengah",City:"Sukamara"},
    {Province:"Kalimantan Timur",City:"Balikpapan"},
    {Province:"Kalimantan Timur",City:"Berau"},
    {Province:"Kalimantan Timur",City:"Bontang"},
    {Province:"Kalimantan Timur",City:"Kutai Barat"},
    {Province:"Kalimantan Timur",City:"Kutai Kartanegara"},
    {Province:"Kalimantan Timur",City:"Kutai Timur"},
    {Province:"Kalimantan Timur",City:"Mahakam Ulu"},
    {Province:"Kalimantan Timur",City:"Paser"},
    {Province:"Kalimantan Timur",City:"Penajam Paser Utara"},
    {Province:"Kalimantan Timur",City:"Samarinda"},
    {Province:"Kalimantan Utara",City:"Bulungan"},
    {Province:"Kalimantan Utara",City:"Malinau"},
    {Province:"Kalimantan Utara",City:"Nunukan"},
    {Province:"Kalimantan Utara",City:"Tana Tidung"},
    {Province:"Kalimantan Utara",City:"Tarakan"},
    {Province:"Kepulauan Riau",City:"Batam"},
    {Province:"Kepulauan Riau",City:"Bintan"},
    {Province:"Kepulauan Riau",City:"Karimun"},
    {Province:"Kepulauan Riau",City:"Kepulauan Anambas"},
    {Province:"Kepulauan Riau",City:"Lingga"},
    {Province:"Kepulauan Riau",City:"Natuna"},
    {Province:"Kepulauan Riau",City:"Tanjung Pinang"},
    {Province:"Lampung",City:"Bandar Lampung"},
    {Province:"Lampung",City:"Lampung Barat"},
    {Province:"Lampung",City:"Lampung Selatan"},
    {Province:"Lampung",City:"Lampung Tengah"},
    {Province:"Lampung",City:"Lampung Timur"},
    {Province:"Lampung",City:"Lampung Utara"},
    {Province:"Lampung",City:"Mesuji"},
    {Province:"Lampung",City:"Metro"},
    {Province:"Lampung",City:"Pesawaran"},
    {Province:"Lampung",City:"Pesisir Barat"},
    {Province:"Lampung",City:"Pringsewu"},
    {Province:"Lampung",City:"Tanggamus"},
    {Province:"Lampung",City:"Tulang Bawang"},
    {Province:"Lampung",City:"Tulang Bawang Barat"},
    {Province:"Lampung",City:"Way Kanan"},
    {Province:"Maluku",City:"Ambon"},
    {Province:"Maluku",City:"Buru"},
    {Province:"Maluku",City:"Buru Selatan"},
    {Province:"Maluku",City:"Kepulauan Aru"},
    {Province:"Maluku",City:"Maluku Barat Daya"},
    {Province:"Maluku",City:"Maluku Tengah"},
    {Province:"Maluku",City:"Maluku Tenggara"},
    {Province:"Maluku",City:"Maluku Tenggara Barat"},
    {Province:"Maluku",City:"Seram Bagian Barat"},
    {Province:"Maluku",City:"Seram Bagian Timur"},
    {Province:"Maluku",City:"Tual"},
    {Province:"Maluku Utara",City:"Halmahera Barat"},
    {Province:"Maluku Utara",City:"Halmahera Selatan"},
    {Province:"Maluku Utara",City:"Halmahera Tengah"},
    {Province:"Maluku Utara",City:"Halmahera Timur"},
    {Province:"Maluku Utara",City:"Halmahera Utara"},
    {Province:"Maluku Utara",City:"Kepulauan Sula"},
    {Province:"Maluku Utara",City:"Pulau Morotai"},
    {Province:"Maluku Utara",City:"Pulau Taliabu"},
    {Province:"Maluku Utara",City:"Ternate"},
    {Province:"Maluku Utara",City:"Tidore Kepulauan"},
    {Province:"Nusa Tenggara Barat (NTB)",City:"Bima"},
    {Province:"Nusa Tenggara Barat (NTB)",City:"Dompu"},
    {Province:"Nusa Tenggara Barat (NTB)",City:"Lombok Barat"},
    {Province:"Nusa Tenggara Barat (NTB)",City:"Lombok Tengah"},
    {Province:"Nusa Tenggara Barat (NTB)",City:"Lombok Timur"},
    {Province:"Nusa Tenggara Barat (NTB)",City:"Lombok Utara"},
    {Province:"Nusa Tenggara Barat (NTB)",City:"Mataram"},
    {Province:"Nusa Tenggara Barat (NTB)",City:"Sumbawa"},
    {Province:"Nusa Tenggara Barat (NTB)",City:"Sumbawa Barat"},
    {Province:"Nusa Tenggara Timur (NTT)",City:" Ende"},
    {Province:"Nusa Tenggara Timur (NTT)",City:" Flores Timur"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Alor"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Belu"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Ende"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Flores Timur"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Kupang"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Lembata"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Malaka"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Manggarai"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Manggarai Barat"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Manggarai Timur"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Nagekeo"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Ngada"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Rote Ndao"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Sabu Raijua"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Sikka"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Sumba Barat"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Sumba Barat Daya"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Sumba Tengah"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Sumba Timur"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Timor Tengah Selatan"},
    {Province:"Nusa Tenggara Timur (NTT)",City:"Timor Tengah Utara"},
    {Province:"Papua",City:"Asmat"},
    {Province:"Papua",City:"Biak Numfor"},
    {Province:"Papua",City:"Boven Digoel"},
    {Province:"Papua",City:"Deiyai"},
    {Province:"Papua",City:"Dogiyai"},
    {Province:"Papua",City:"Intan Jaya"},
    {Province:"Papua",City:"Jayapura"},
    {Province:"Papua",City:"Jayawijaya"},
    {Province:"Papua",City:"Keerom"},
    {Province:"Papua",City:"Kepulauan Yapen"},
    {Province:"Papua",City:"Lanny Jaya"},
    {Province:"Papua",City:"Mamberamo Raya"},
    {Province:"Papua",City:"Mamberamo Tengah"},
    {Province:"Papua",City:"Mappi"},
    {Province:"Papua",City:"Merauke"},
    {Province:"Papua",City:"Mimika"},
    {Province:"Papua",City:"Nabire"},
    {Province:"Papua",City:"Nduga"},
    {Province:"Papua",City:"Paniai"},
    {Province:"Papua",City:"Pegunungan Bintang"},
    {Province:"Papua",City:"Puncak"},
    {Province:"Papua",City:"Puncak Jaya"},
    {Province:"Papua",City:"Sarmi"},
    {Province:"Papua",City:"Supiori"},
    {Province:"Papua",City:"Tolikara"},
    {Province:"Papua",City:"Waropen"},
    {Province:"Papua",City:"Yahukimo"},
    {Province:"Papua",City:"Yalimo"},
    {Province:"Papua Barat",City:"Fakfak"},
    {Province:"Papua Barat",City:"Kaimana"},
    {Province:"Papua Barat",City:"Manokwari"},
    {Province:"Papua Barat",City:"Manokwari Selatan"},
    {Province:"Papua Barat",City:"Maybrat"},
    {Province:"Papua Barat",City:"Pegunungan Arfak"},
    {Province:"Papua Barat",City:"Raja Ampat"},
    {Province:"Papua Barat",City:"Sorong"},
    {Province:"Papua Barat",City:"Sorong Selatan"},
    {Province:"Papua Barat",City:"Tambrauw"},
    {Province:"Papua Barat",City:"Teluk Bintuni"},
    {Province:"Papua Barat",City:"Teluk Wondama"},
    {Province:"Riau",City:"Bengkalis"},
    {Province:"Riau",City:"Dumai"},
    {Province:"Riau",City:"Indragiri Hilir"},
    {Province:"Riau",City:"Indragiri Hulu"},
    {Province:"Riau",City:"Kampar"},
    {Province:"Riau",City:"Kepulauan Meranti"},
    {Province:"Riau",City:"Kuantan Singingi"},
    {Province:"Riau",City:"Pekanbaru"},
    {Province:"Riau",City:"Pelalawan"},
    {Province:"Riau",City:"Rokan Hilir"},
    {Province:"Riau",City:"Rokan Hulu"},
    {Province:"Riau",City:"Siak"},
    {Province:"Sulawesi Barat",City:"Majene"},
    {Province:"Sulawesi Barat",City:"Mamasa"},
    {Province:"Sulawesi Barat",City:"Mamuju"},
    {Province:"Sulawesi Barat",City:"Mamuju Tengah"},
    {Province:"Sulawesi Barat",City:"Mamuju Utara"},
    {Province:"Sulawesi Barat",City:"Polewali Mandar"},
    {Province:"Sulawesi Selatan",City:"Bantaeng"},
    {Province:"Sulawesi Selatan",City:"Barru"},
    {Province:"Sulawesi Selatan",City:"Bone"},
    {Province:"Sulawesi Selatan",City:"Bulukumba"},
    {Province:"Sulawesi Selatan",City:"Enrekang"},
    {Province:"Sulawesi Selatan",City:"Gowa"},
    {Province:"Sulawesi Selatan",City:"Jeneponto"},
    {Province:"Sulawesi Selatan",City:"Kepulauan Selayar"},
    {Province:"Sulawesi Selatan",City:"Luwu"},
    {Province:"Sulawesi Selatan",City:"Luwu Timur"},
    {Province:"Sulawesi Selatan",City:"Luwu Utara"},
    {Province:"Sulawesi Selatan",City:"Makassar"},
    {Province:"Sulawesi Selatan",City:"Maros"},
    {Province:"Sulawesi Selatan",City:"Palopo"},
    {Province:"Sulawesi Selatan",City:"Pangkajene Kepulauan"},
    {Province:"Sulawesi Selatan",City:"Parepare"},
    {Province:"Sulawesi Selatan",City:"Pinrang"},
    {Province:"Sulawesi Selatan",City:"Sidenreng Rappang"},
    {Province:"Sulawesi Selatan",City:"Sinjai"},
    {Province:"Sulawesi Selatan",City:"Soppeng"},
    {Province:"Sulawesi Selatan",City:"Takalar"},
    {Province:"Sulawesi Selatan",City:"Tana Toraja"},
    {Province:"Sulawesi Selatan",City:"Toraja Utara"},
    {Province:"Sulawesi Selatan",City:"Wajo"},
    {Province:"Sulawesi Tengah",City:"Banggai"},
    {Province:"Sulawesi Tengah",City:"Banggai Kepulauan"},
    {Province:"Sulawesi Tengah",City:"Banggai Laut"},
    {Province:"Sulawesi Tengah",City:"Buol"},
    {Province:"Sulawesi Tengah",City:"Donggala"},
    {Province:"Sulawesi Tengah",City:"Morowali"},
    {Province:"Sulawesi Tengah",City:"Morowali Utara"},
    {Province:"Sulawesi Tengah",City:"Palu"},
    {Province:"Sulawesi Tengah",City:"Parigi Moutong"},
    {Province:"Sulawesi Tengah",City:"Poso"},
    {Province:"Sulawesi Tengah",City:"Sigi"},
    {Province:"Sulawesi Tengah",City:"Tojo Una-Una"},
    {Province:"Sulawesi Tengah",City:"Toli-Toli"},
    {Province:"Sulawesi Tenggara",City:"Bau-Bau"},
    {Province:"Sulawesi Tenggara",City:"Bombana"},
    {Province:"Sulawesi Tenggara",City:"Buton"},
    {Province:"Sulawesi Tenggara",City:"Buton Selatan"},
    {Province:"Sulawesi Tenggara",City:"Buton Tengah"},
    {Province:"Sulawesi Tenggara",City:"Buton Utara"},
    {Province:"Sulawesi Tenggara",City:"Kendari"},
    {Province:"Sulawesi Tenggara",City:"Kolaka"},
    {Province:"Sulawesi Tenggara",City:"Kolaka Timur"},
    {Province:"Sulawesi Tenggara",City:"Kolaka Utara"},
    {Province:"Sulawesi Tenggara",City:"Konawe"},
    {Province:"Sulawesi Tenggara",City:"Konawe Kepulauan"},
    {Province:"Sulawesi Tenggara",City:"Konawe Selatan"},
    {Province:"Sulawesi Tenggara",City:"Konawe Utara"},
    {Province:"Sulawesi Tenggara",City:"Muna"},
    {Province:"Sulawesi Tenggara",City:"Muna Barat"},
    {Province:"Sulawesi Tenggara",City:"Wakatobi"},
    {Province:"Sulawesi Utara",City:"Bitung"},
    {Province:"Sulawesi Utara",City:"Bolaang Mongondow"},
    {Province:"Sulawesi Utara",City:"Bolaang Mongondow Selatan"},
    {Province:"Sulawesi Utara",City:"Bolaang Mongondow Timur"},
    {Province:"Sulawesi Utara",City:"Bolaang Mongondow Utara"},
    {Province:"Sulawesi Utara",City:"Kepulauan Sangihe"},
    {Province:"Sulawesi Utara",City:"Kepulauan Siau Tagulandang Biaro (Sitaro)"},
    {Province:"Sulawesi Utara",City:"Kepulauan Talaud"},
    {Province:"Sulawesi Utara",City:"Kotamobagu"},
    {Province:"Sulawesi Utara",City:"Manado"},
    {Province:"Sulawesi Utara",City:"Minahasa"},
    {Province:"Sulawesi Utara",City:"Minahasa Selatan"},
    {Province:"Sulawesi Utara",City:"Minahasa Tenggara"},
    {Province:"Sulawesi Utara",City:"Minahasa Utara"},
    {Province:"Sulawesi Utara",City:"Tomohon"},
    {Province:"Sumatera Barat",City:"Agam"},
    {Province:"Sumatera Barat",City:"Bukittinggi"},
    {Province:"Sumatera Barat",City:"Dharmasraya"},
    {Province:"Sumatera Barat",City:"Kepulauan Mentawai"},
    {Province:"Sumatera Barat",City:"Lima Puluh Kota"},
    {Province:"Sumatera Barat",City:"Padang"},
    {Province:"Sumatera Barat",City:"Padang Panjang"},
    {Province:"Sumatera Barat",City:"Padang Pariaman"},
    {Province:"Sumatera Barat",City:"Pariaman"},
    {Province:"Sumatera Barat",City:"Pasaman"},
    {Province:"Sumatera Barat",City:"Pasaman Barat"},
    {Province:"Sumatera Barat",City:"Payakumbuh"},
    {Province:"Sumatera Barat",City:"Pesisir Selatan"},
    {Province:"Sumatera Barat",City:"Sawah Lunto"},
    {Province:"Sumatera Barat",City:"Sijunjung"},
    {Province:"Sumatera Barat",City:"Solok"},
    {Province:"Sumatera Barat",City:"Solok Selatan"},
    {Province:"Sumatera Barat",City:"Tanah Datar"},
    {Province:"Sumatera Selatan",City:"Banyuasin"},
    {Province:"Sumatera Selatan",City:"Empat Lawang"},
    {Province:"Sumatera Selatan",City:"Lahat"},
    {Province:"Sumatera Selatan",City:"Lubuk Linggau"},
    {Province:"Sumatera Selatan",City:"Muara Enim"},
    {Province:"Sumatera Selatan",City:"Musi Banyuasin"},
    {Province:"Sumatera Selatan",City:"Musi Rawas"},
    {Province:"Sumatera Selatan",City:"Musi Rawas Utara"},
    {Province:"Sumatera Selatan",City:"Ogan Ilir"},
    {Province:"Sumatera Selatan",City:"Ogan Komering Ilir"},
    {Province:"Sumatera Selatan",City:"Ogan Komering Ulu"},
    {Province:"Sumatera Selatan",City:"Ogan Komering Ulu Selatan"},
    {Province:"Sumatera Selatan",City:"Ogan Komering Ulu Timur"},
    {Province:"Sumatera Selatan",City:"Pagar Alam"},
    {Province:"Sumatera Selatan",City:"Palembang"},
    {Province:"Sumatera Selatan",City:"Penukal Abab Lematang Ilir"},
    {Province:"Sumatera Selatan",City:"Prabumulih"},
    {Province:"Sumatera Utara",City:"Asahan"},
    {Province:"Sumatera Utara",City:"Batu Bara"},
    {Province:"Sumatera Utara",City:"Binjai"},
    {Province:"Sumatera Utara",City:"Dairi"},
    {Province:"Sumatera Utara",City:"Deli Serdang"},
    {Province:"Sumatera Utara",City:"Gunungsitoli"},
    {Province:"Sumatera Utara",City:"Humbang Hasundutan"},
    {Province:"Sumatera Utara",City:"Karo"},
    {Province:"Sumatera Utara",City:"Labuhanbatu"},
    {Province:"Sumatera Utara",City:"Labuhanbatu Selatan"},
    {Province:"Sumatera Utara",City:"Labuhanbatu Utara"},
    {Province:"Sumatera Utara",City:"Langkat"},
    {Province:"Sumatera Utara",City:"Mandailing Natal"},
    {Province:"Sumatera Utara",City:"Medan"},
    {Province:"Sumatera Utara",City:"Nias"},
    {Province:"Sumatera Utara",City:"Nias Barat"},
    {Province:"Sumatera Utara",City:"Nias Selatan"},
    {Province:"Sumatera Utara",City:"Nias Utara"},
    {Province:"Sumatera Utara",City:"Padang Lawas"},
    {Province:"Sumatera Utara",City:"Padang Lawas Utara"},
    {Province:"Sumatera Utara",City:"Padang Sidempuan"},
    {Province:"Sumatera Utara",City:"Pakpak Bharat"},
    {Province:"Sumatera Utara",City:"Pematang Siantar"},
    {Province:"Sumatera Utara",City:"Samosir"},
    {Province:"Sumatera Utara",City:"Serdang Bedagai"},
    {Province:"Sumatera Utara",City:"Sibolga"},
    {Province:"Sumatera Utara",City:"Simalungun"},
    {Province:"Sumatera Utara",City:"Tanjung Balai"},
    {Province:"Sumatera Utara",City:"Tapanuli Selatan"},
    {Province:"Sumatera Utara",City:"Tapanuli Tengah"},
    {Province:"Sumatera Utara",City:"Tapanuli Utara"},
    {Province:"Sumatera Utara",City:"Tebing Tinggi"},
    {Province:"Sumatera Utara",City:"Toba Samosir"},
    ]

    // 获取省级列表
    const getProvince=()=>{
        let provinceData=[]
        Address.map((item)=>{
            provinceData.push(item.Province)
        })
        for(var i = 0; i < provinceData.length-1; i++){
            for(var j = i+1; j < provinceData.length; j++){
                if(provinceData[i]===provinceData[j]){
                    provinceData.splice(j,1);
                    j--;
                }
            }
        }
        return provinceData
    }

    // 获取某省的市级列表(需要传入一个省名称)
    const getCity=(province)=>{
        let city=[]
        Address.map((item)=>{
            if(item.Province===province){
                city.push(item.City)
            }
        })
        return city
    }

    export {getProvince,getCity}